### ISSUE TITLE
Astah font

### ISSUE THREAD

**Issue by vbsessa** [tuxjdk/tuxjdk#2] opened 2015-06-22 20:44 UTC
Hello again...

Astah is rendering fonts very weird under Tuxjdk. Take a look...
![astah](https://cloud.githubusercontent.com/assets/2204164/8292481/47324112-1906-11e5-9a01-e45376ae9c2b.png)

**Comment by TheIndifferent** [comment] 2015-06-22 21:34
That indeed looks weird. I've downloaded Astah and tried on my system, looks perfectly fine for me. Could you please take a screenshot of System Properties - Diagram Editor window? And also could you make the same screenshot with oracle java? I'll try to debug which font Astah requests and compare the rendering.

**Comment by vbsessa** [comment] 2015-06-22 23:26
My Java logical font "Dialog" maps to Droid Sans, just to know :)

Oracle JDK

![astah-2](https://cloud.githubusercontent.com/assets/2204164/8295611/c4163ac4-191c-11e5-8dd1-dea2c9a1b2c1.png)

**Comment by TheIndifferent** [comment] 2015-06-23 08:13
Droid Sans, ok, will try that. And that's on Fedora 22 inside the VM?

**Comment by vbsessa** [comment] 2015-06-23 12:07
Yes.

**Comment by vbsessa** [comment] 2015-06-23 14:21
Hi, i'm facing the same issue in intellij IDEA and Netbeans code snippets.
See:

#### Intellij IDEA
![idea](https://cloud.githubusercontent.com/assets/2204164/8308199/e85b1b3e-1999-11e5-8c19-dfbe80cc9cea.png)

**Comment by TheIndifferent** [comment] 2015-06-23 14:26
Thanx for noting that. Hopefully I'll be able to hunt it down and fix it till next Monday.

Could you also clarify about NetBeans code sniplets, you mean when you put mouse over the collapsed code block and it is shown in custom tooltip?

**Comment by vbsessa** [comment] 2015-06-23 14:29
That's right.

**Comment by TheIndifferent** [comment] 2015-06-23 14:30
And the last question before I'm installing Fedora :) are you using Gnome-Shell or one of the spins?

**Comment by vbsessa** [comment] 2015-06-23 14:31
Gnome-Shell

**Comment by TheIndifferent** [comment] 2015-06-23 17:01
I'll try to reproduce the issue with Fedora, if it will look ok for me then I'll ask you to share your /etc/fonts folder. I wrote openjdk-fontfix really long time ago, and since that time I found couple of critical issues, so unless someone else fixed it - it should not work on Fedora at all.

**Comment by vbsessa** [comment] 2015-06-23 17:04
Ohh.. i see.
I'm a little lost about these font patches, but what's the relation between TuxJDK, Infinality and Bohoomil?

**Comment by TheIndifferent** [comment] 2015-06-23 17:15
Freetype2 is responsible for translating font files (usually TTF) into images.
Fontconfig is a way to configure system fonts and their rendering.
Subpixel antialiasing is patented in US, so most distributions cannot provide it enabled out of the box.
You can rebuild freetype2 to enable subpixel antialiasing if you're living outside of US.
Infinality is series of patches to freetype2, including enabling of subpixels, but in addition they say that their rendering is even better and they provide a huge set of fontconfig configurations optimized for their patches. I don't really trust them, I trust original developers of freetype2 more, so I'm avoiding that.
No idea what's bohoomil, never seen it in action.

And tuxjdk is not really related to them, it is just an attempt to improve font rendering by recreating the same rendering path as proper UI toolkits are doing, such as Qt. So the goal is to make swing fonts identical to Qt fonts, including the possibility of subpixel rendering.

**Comment by vbsessa** [comment] 2015-06-23 17:21
Hummm... As i can see bohoomil looks like an evolution of infinality. But never mind...
I don't think i've said that but i'm using freetype-freeworld here, a rebuilt version of freetype you already mentioned.

**Comment by TheIndifferent** [comment] 2015-06-23 20:10
Ok, I've just tried to reproduce the issue with fresh installation of Fedora 22 with Gnome Shell, no luck. So please share your /etc/fonts dir and give me the link where you got your freetype from.

**Comment by vbsessa** [comment] 2015-06-23 20:28
I've got it from rpm-fusion (free/non-free) repo. A package called freetype-freeworld.

#### /etc/fonts.conf
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <match target="font">
    <edit name="autohint" mode="assign">
      <bool>true</bool>
    </edit>
  </match>
  <match target="font">
    <edit name="rgba" mode="assign">
      <const>rgb</const>
    </edit>
  </match>
  <match target="font">
    <edit name="hintstyle" mode="assign">
      <const>hintslight</const>
    </edit>
  </match>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Droid Serif</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Droid Sans</family>
    </prefer>
  </alias>
  <alias>
    <family>sans</family>
    <prefer>
      <family>Droid Sans</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Consolas</family>
    </prefer>
  </alias>
  <alias>
    <family>dialog</family>
    <prefer>
      <family>Droid Sans</family>
    </prefer>
  </alias>
  <alias>
    <family>dialoginput</family>
    <prefer>
      <family>Consolas</family>
    </prefer>
  </alias>
</fontconfig>
```

PS: Could you make the tar.gz available for download?

**Comment by TheIndifferent** [comment] 2015-06-23 20:42
RPM should be relocatable, you can just unpack the rpm and move wherever you want. I'm not sure tar.gz will be portable between different platforms, there were some ABI changes when apps moved to gcc5, plus I'm not sure how exactly force full static build of everything.

**Comment by vbsessa** [comment] 2015-06-23 20:49
I used rpm2cpio to extract it. Worked pretty though.. :-)
Now the issues are exactly the same under Ubuntu and Fedora. (Ubuntu extracting the rpm and Fedora using the repo)

**Comment by TheIndifferent** [comment] 2015-06-23 21:06
ok, got it reproduced with Astah, was not able to reproduce with NetBeans. Will try to debug it.

**Comment by TheIndifferent** [comment] 2015-06-25 20:56
That is strange, rendering is different depending if you had freeworld installed during the build. There should be no compile-time dependencies in the code. Will check if the requested font is identical...

**Comment by TheIndifferent** [comment] 2015-06-26 10:34
Looks like Astah source code is obfuscated, I will not be able to dig the rendering path they are using. Could you please attach the screenshot from NetBeans, because I am not able to reproduce it with NetBeans at the moment?

**Comment by vbsessa** [comment] 2015-06-26 12:13
My bad, Netbeans collapsed code is beeing reproduced fine. Intellij IDEA is the one, as shown in the screenshot above. Sorry...

**Comment by TheIndifferent** [comment] 2015-06-26 19:38
Ok, debugging through IDEA code showed the issue, it happens when drawing onto BufferedImage. Now have to find how to fix it.

**Comment by TheIndifferent** [comment] 2015-06-27 20:15
Ok, spent a lot of time debugging and reproducing the issue. Now I have one suspicion. Could you please share a screenshot of gedit or any other gnome application, with some text on white background in it?

**Comment by vbsessa** [comment] 2015-06-27 20:33
Gedit
![captura de tela de 2015-06-27 17-31-20](https://cloud.githubusercontent.com/assets/2204164/8393711/71492c1e-1cf2-11e5-89be-32d229c1b033.png)

**Comment by TheIndifferent** [comment] 2015-06-27 21:19
Try adding following block to your fonts conf and check again:
```
	<match target="font">
		<edit mode="assign" name="antialias">
			<bool>true</bool>
		</edit>
	</match>
```

**Comment by vbsessa** [comment] 2015-06-27 23:28
Same thing...
![captura de tela de 2015-06-27 20-28-16](https://cloud.githubusercontent.com/assets/2204164/8394377/1928d4c6-1d0b-11e5-8a81-bce071da635f.png)

**Comment by TheIndifferent** [comment] 2015-06-28 09:07
With gedit yes, but what about IDEA and Astah? For me they became much better.

**Comment by vbsessa** [comment] 2015-06-28 12:26
Everything is the same :(
Can i see a screenshot?

**Comment by TheIndifferent** [comment] 2015-06-28 12:48
Astah as you probably see it:
![fedora-no-antialias](https://cloud.githubusercontent.com/assets/9323482/8396398/bb98072a-1da3-11e5-87a2-1bd7b641377d.png)

Astah after I'm adding that fontconfig block I've posted above:
![fedora-antialias](https://cloud.githubusercontent.com/assets/9323482/8396403/cb8892bc-1da3-11e5-8da9-1a2925be4c88.png)


If you will zoom in the screenshots, it is obvious that by default UI of astah is using grayscale antialiasing. With tuxjdk the default config is lcd antialiasing, which does not work because query to the fontconfig does not show antialiasing as enabled, that's why the text on first image looks weird. Enabling antialiasing through fontconfig allows tuxjdk to use it, that's why on second image astah UI still uses grayscale, but instead of weird fonts you can see proper lcd antialiased fonts.

Another simple solution is to enable grayscale antialiasing in tuxjdk, fonts will look fine, especially considering that astah is already using grayscale everywhere. Here's how:
```
echo 'ui.defaultFont.antialiasing=on' >~/.config/java.properties
```

Please report back which of those worked for you. I will add couple more items in TODO list, first of all is transforming of "on" into either "lcd" or "grayscale", and second is design of some small app to create a proper config on postinstall, depending on LCD availability in freetype.

**Comment by vbsessa** [comment] 2015-06-28 13:06
Using
```
echo 'ui.defaultFont.antialiasing=on' > ~/.config/java.properties
```
fixed Astah, but IDEA is the same.

**Comment by TheIndifferent** [comment] 2015-06-28 13:16
Hm, looks like another TODO point, to reimplement logic behing awt.useSystemAAFontSettings. Try this:
```
sed -i 's/awt.useSystemAAFontSettings=lcd/awt.useSystemAAFontSettings=on/' idea-IC-141.1532.4/bin/idea64.vmoptions
```

**Comment by vbsessa** [comment] 2015-06-28 13:24
I just added these props to fonts.conf and that fixed EVERYTHING!!!
All fonts are AWESOME now! :-)
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="font">
        <edit name="autohint" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="hinting" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="hintstyle" mode="assign">
            <const>hintslight</const>
        </edit>
        <edit name="antialias" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="lcdfilter" mode="assign">
            <const>lcddefault</const>
        </edit>
        <edit name="rgba" mode="assign">
            <const>rgb</const>
        </edit>
    </match>
 [...]
```

**Comment by vbsessa** [comment] 2015-06-28 13:27
Actually, that improved regular fonts a little too. I think adjust rgba through gnome-tweak-tool hasn't the same effect as editing fonts.conf properly.

Man, I own you one!

**Comment by TheIndifferent** [comment] 2015-06-28 14:00
Hm, I thought you already had those properties, only missing was antialias. But good to know that it is solved now.

I've noticed too that fc-match and fc-pattern do not show antialiasing, but your gnome screenshots are still using it. No idea what have they done.

Have you tried changing back to ui.defaultFont.antialiasing=lcd in ~/.config/java.properties ? If no - please try it and tell me if it reverts to being weird or works properly and with coloured antialiasing.

**Comment by vbsessa** [comment] 2015-06-28 14:07
Yes, i removed the `java.properties` file from `~/.config` dir because `ui.defaultFont.antialiasing=on` was the only line there. I mean, the file didn't exist before that command. Everything is still fine.

**Comment by TheIndifferent** [comment] 2015-06-28 14:17
Great. Thanx for the report, revealed some pretty interesting issues. I'm closing the issue, and will expand TODO list.

**Closed** 2015-06-28 14:21 UTC
